<?php

namespace classes;
include "../classes/converter.php";
include "../classes/temperature/temperature.php";
include "../classes/temperature/celsius.php";

/**
 * Generated by PHPUnit_SkeletonGenerator on 2017-10-10 at 10:53:55.
 */
class ConverterTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Converter
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $temperature = new temperature\Celsius(10);
        $this->object = new Converter($temperature, "fahrenheit");
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers classes\Converter::convert
     * @todo   Implement testConvert().
     */
    public function testConvert() {
        $this->assertEquals(50, $this->object->convert());
    }

    /**
     * @covers classes\Converter::getTemperature
     * @todo   Implement testGetTemperature().
     */
    public function testGetTemperature() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Converter::setTemperature
     * @todo   Implement testSetTemperature().
     */
    public function testSetTemperature() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Converter::getTarget
     * @todo   Implement testGetTarget().
     */
    public function testGetTarget() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers classes\Converter::setTarget
     * @todo   Implement testSetTarget().
     */
    public function testSetTarget() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
